### ISSUE TITLE
ci: audit Django test apps

### ISSUE THREAD

**Issue by timgraham** [googleapis/python-spanner-django#317]
I'm auditing the list of Django test apps in `.travis.yml`. CI is running many which are unnecessary (no database interaction). Also, some folders in django/tests don't include any tests.

- [x] absolute_url_overrides (no database interaction)
- [x] admin_autodiscover (no database interaction)
- [x] admin_changelist
- [x] admin_checks (no database interaction)
- [x] admin_custom_urls (no database interaction)
- [x] admin_default_site (no database interaction)
- [x] admin_docs
- [x] admin_filters
- [x] admin_inlines
- [x] admin_ordering
- [x] admin_registration (no database interaction)
- [x] admin_scripts (no database interaction)
- [X] admin_utils (https://github.com/orijtech/django-spanner/issues/150)
- [x] admin_views
- [x] admin_widgets (unlikely to add test coverage)
- [x] aggregation
- [x] aggregation_regress
- [x] annotations
- [x] app_loading (no database interaction)
- [x] apps (no database interaction)
- [x] auth_tests
- [x] backends (https://github.com/orijtech/django-spanner/issues/318)
- [x] base (no tests)
- [x] bash_completion (no database interaction)
- [x] basic
- [x] builtin_server (no database interaction)
- [x] bulk_create
- [x] cache
- [x] check_framework (no database interaction)
- [x] choices
- [x] conditional_processing (no database interaction)
- [x] constraints
- [x] contenttypes_tests (#396)
- [x] context_processors (no database interaction)
- [x] csrf_tests (no database interaction)
- [x] custom_columns
- [x] custom_lookups
- [x] custom_managers
- [x] custom_methods
- [x] custom_migration_operations (no tests)
- [x] custom_pk
- [x] datatypes
- [x] dates
- [x] datetimes
- [x] db_functions
- [x] dbshell (no database interaction)
- [x] db_typecasts (no database interaction)
- [x] db_utils (no database interaction)
- [x] decorators (no database interaction)
- [x] defer
- [x] defer_regress
- [x] delete
- [x] delete_regress
- [x] deprecation (no database interaction)
- [x] dispatch (no database interaction)
- [x] distinct_on_fields
- [x] empty
- [x] expressions
- [x] expressions_case (https://github.com/orijtech/django-spanner/issues/353)
- [x] expressions_window
- [x] extra_regress
- [x] field_deconstruction (no database interaction)
- [x] field_defaults
- [x] field_subclassing (no database interaction)
- [x] files (no database interaction)
- [x] file_storage
- [x] file_uploads
- [x] filtered_relation
- [x] fixtures
- [x] fixtures_model_package
- [x] fixtures_regress
- [x] flatpages_tests
- [x] force_insert_update (https://github.com/googleapis/python-spanner-django/issues/420)
- [x] foreign_object (https://github.com/googleapis/python-spanner-django/issues/421)
- [x] forms_tests
- [x] from_db_value
- [x] generic_inline_admin
- [x] generic_relations
- [x] generic_relations_regress
- [x] generic_views
- [x] get_earliest_or_latest
- [x] get_object_or_404
- [X] get_or_create (#270)
- [x] gis_tests (not applicable)
- [x] handlers (no database interaction)
- [x] httpwrappers (no database interaction)
- [x] humanize_tests (no database interaction)
- [x] i18n
- [x] import_error_package (no tests)
- [x] indexes
- [x] inline_formsets
- [x] inspectdb
- [x] introspection
- [x] invalid_models_tests
- [x] known_related_objects
- [x] logging_tests (no database interaction)
- [x] lookup
- [x] m2m_and_m2o
- [x] m2m_intermediary
- [x] m2m_multiple
- [x] m2m_recursive
- [x] m2m_regress
- [x] m2m_signals
- [x] m2m_through
- [x] m2m_through_regress
- [x] m2o_recursive
- [x] mail  (no database interaction)
- [x] managers_regress
- [x] many_to_many
- [x] many_to_one
- [x] many_to_one_null
- [x] max_lengths
- [x] messages_tests (no database interaction)
- [x] middleware (no database interaction)
- [x] middleware_exceptions (no database interaction)
- [x] migrate_signals
- [x] migrations
- [x] migrations2 (no tests)
- [x] migration_test_data_persistence
- [x] modeladmin
- [x] model_fields
- [x] model_forms
- [x] model_formsets
- [x] model_formsets_regress
- [x] model_indexes
- [x] model_inheritance
- [x] model_inheritance_regress
- [x] model_meta (no database interaction)
- [x] model_options
- [x] model_package
- [x] model_regress
- [x] multiple_database
- [x] mutually_referential
- [x] nested_foreign_keys
- [x] no_models (no database interaction)
- [x] null_fk
- [x] null_fk_ordering
- [x] null_queries
- [x] one_to_one
- [x] ordering
- [x] order_with_respect_to (#396)
- [x] or_lookups
- [x] pagination (all tests assume ordering by a serial pk)
- [x] postgres_tests (not applicable)
- [x] prefetch_related
- [x] project_template (no database interaction)
- [x] properties (no database interaction)
- [x] proxy_model_inheritance
- [x] proxy_models
- [x] queries
- [x] queryset_pickle
- [x] raw_query
- [x] redirects_tests
- [x] requests_ (no database interaction)
- [x] requirements (no tests)
- [x] reserved_names
- [x] resolve_url (no database interaction)
- [x] responses (no database interaction)
- [x] reverse_lookup
- [x] save_delete_hooks
- [x] schema
- [x] select_for_update
- [x] select_related
- [x] select_related_onetoone
- [x] select_related_regress
- [x] serializers
- [x] servers
- [X] sessions_tests (https://github.com/orijtech/django-spanner/pull/395)
- [x] settings_tests (no database interaction)
- [x] shell (no database interaction)
- [x] shortcuts (no database interaction)
- [x] signals
- [x] signed_cookies_tests (no database interaction)
- [x] signing (no database interaction)
- [x] sitemaps_tests
- [x] sites_framework
- [x] sites_tests
- [x] staticfiles_tests (no database interaction)
- [x] str (no database interaction)
- [x] string_lookup
- [x] swappable_models (no database interaction)
- [x] syndication_tests
- [x] template_backends (no database interaction)
- [x] template_loader (no database interaction)
- [x] templates (no tests)
- [x] template_tests (no database interaction)
- [x] test_client
- [x] test_client_regress
- [x] test_exceptions (no database interaction)
- [x] test_runner
- [x] test_runner_apps (no tests)
- [x] test_utils
- [x] timezones
- [x] transaction_hooks
- [x] transactions
- [x] unmanaged_models
- [x] update
- [x] update_only_fields
- [x] urlpatterns (no database interaction)
- [x] urlpatterns_reverse (no database interaction)
- [x] user_commands (no database interaction)
- [x] utils_tests (no database interaction)
- [x] validation
- [x] validators (no database interaction)
- [x] version (no database interaction)
- [x] view_tests
- [x] wsgi (no database interaction)
